import { useState, useEffect } from 'react';
import QRCode from 'qrcode';
import { useWarehouse } from '../context/WarehouseContext';
import type { Unit } from '../types';

export function PrintButton() {
  const { units, layout } = useWarehouse();
  const [showMenu, setShowMenu] = useState(false);

  const handlePrintInventorySummary = async () => {
    setShowMenu(false);

    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const totalValue = units.reduce((sum, unit) => sum + (unit.purchasePrice || 0), 0);
    const statusCounts = units.reduce((acc, unit) => {
      acc[unit.status] = (acc[unit.status] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    const zoneCounts = units.reduce((acc, unit) => {
      const zoneName = layout.zones.find(z => z.id === unit.location.zone)?.name || unit.location.zone;
      acc[zoneName] = (acc[zoneName] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Inventory Summary - ${new Date().toLocaleDateString()}</title>
          <style>
            @page { margin: 0.5in; }
            body {
              font-family: Arial, sans-serif;
              padding: 20px;
            }
            h1 {
              color: #000080;
              border-bottom: 3px solid #000080;
              padding-bottom: 10px;
            }
            h2 {
              color: #000080;
              margin-top: 30px;
              border-bottom: 2px solid #7f9db9;
              padding-bottom: 5px;
            }
            .summary-grid {
              display: grid;
              grid-template-columns: 1fr 1fr;
              gap: 20px;
              margin: 20px 0;
            }
            .summary-box {
              border: 2px solid #7f9db9;
              padding: 15px;
              background: #f5f5f5;
            }
            .summary-box h3 {
              margin-top: 0;
              color: #000080;
            }
            .stat-row {
              display: flex;
              justify-content: space-between;
              padding: 5px 0;
              border-bottom: 1px solid #ddd;
            }
            .stat-label {
              font-weight: bold;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
            }
            th, td {
              border: 1px solid #7f9db9;
              padding: 8px;
              text-align: left;
            }
            th {
              background: #000080;
              color: white;
            }
            tr:nth-child(even) {
              background: #f5f5f5;
            }
            .footer {
              margin-top: 40px;
              text-align: center;
              font-size: 12px;
              color: #666;
            }
          </style>
        </head>
        <body>
          <h1>Warehouse Inventory Summary</h1>
          <p><strong>Report Date:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Total Units:</strong> ${units.length}</p>

          <div class="summary-grid">
            <div class="summary-box">
              <h3>Status Breakdown</h3>
              ${Object.entries(statusCounts).map(([status, count]) => `
                <div class="stat-row">
                  <span class="stat-label">${status}:</span>
                  <span>${count}</span>
                </div>
              `).join('')}
            </div>

            <div class="summary-box">
              <h3>Financial Summary</h3>
              <div class="stat-row">
                <span class="stat-label">Total Inventory Value:</span>
                <span>${new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(totalValue)}</span>
              </div>
              <div class="stat-row">
                <span class="stat-label">Units with Price Data:</span>
                <span>${units.filter(u => u.purchasePrice).length}</span>
              </div>
            </div>
          </div>

          <h2>Units by Zone</h2>
          <div class="summary-box">
            ${Object.entries(zoneCounts).map(([zone, count]) => `
              <div class="stat-row">
                <span class="stat-label">${zone}:</span>
                <span>${count} units</span>
              </div>
            `).join('')}
          </div>

          <div class="footer">
            <p>Generated by Warehouse Management System</p>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.print();
  };

  const handlePrintAllUnits = () => {
    setShowMenu(false);

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const getLocationText = (unit: Unit) => {
      const zoneName = layout.zones.find(z => z.id === unit.location.zone)?.name || unit.location.zone;
      if (unit.location.type === 'floor') {
        return zoneName;
      } else {
        return `${zoneName} - C${unit.location.column}R${unit.location.row}L${unit.location.level}`;
      }
    };

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>All Units - ${new Date().toLocaleDateString()}</title>
          <style>
            @page { margin: 0.5in; }
            body {
              font-family: Arial, sans-serif;
              padding: 20px;
            }
            h1 {
              color: #000080;
              border-bottom: 3px solid #000080;
              padding-bottom: 10px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
              font-size: 11px;
            }
            th, td {
              border: 1px solid #7f9db9;
              padding: 6px;
              text-align: left;
            }
            th {
              background: #000080;
              color: white;
              font-weight: bold;
            }
            tr:nth-child(even) {
              background: #f5f5f5;
            }
            .footer {
              margin-top: 20px;
              text-align: center;
              font-size: 12px;
              color: #666;
            }
          </style>
        </head>
        <body>
          <h1>All Units Report</h1>
          <p><strong>Report Date:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Total Units:</strong> ${units.length}</p>

          <table>
            <thead>
              <tr>
                <th>Serial Number</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Status</th>
                <th>Condition</th>
                <th>Location</th>
                <th>Purchase Price</th>
                <th>Date Added</th>
              </tr>
            </thead>
            <tbody>
              ${units.map(unit => `
                <tr>
                  <td>${unit.serialNumber}</td>
                  <td>${unit.brand}</td>
                  <td>${unit.model}</td>
                  <td>${unit.status}</td>
                  <td>${unit.condition || '-'}</td>
                  <td>${getLocationText(unit)}</td>
                  <td>${unit.purchasePrice ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(unit.purchasePrice) : '-'}</td>
                  <td>${unit.createdDate ? new Date(unit.createdDate).toLocaleDateString() : '-'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="footer">
            <p>Generated by Warehouse Management System</p>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="relative">
      <button
        onClick={() => setShowMenu(!showMenu)}
        className="text-white font-bold py-2 px-4 rounded transition-all text-sm"
        title="Print Reports"
        style={{
          background: 'linear-gradient(to bottom, #87ceeb 0%, #4169e1 50%, #1e90ff 100%)',
          border: '2px solid #1e90ff',
          borderTopColor: '#b0d4ff',
          borderLeftColor: '#b0d4ff',
          textShadow: '1px 1px 1px rgba(0,0,0,0.3)',
          fontFamily: 'Tahoma, sans-serif'
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.background = 'linear-gradient(to bottom, #a0d8f0 0%, #5a7fe6 50%, #3da0ff 100%)';
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.background = 'linear-gradient(to bottom, #87ceeb 0%, #4169e1 50%, #1e90ff 100%)';
        }}
      >
        Print ▼
      </button>

      {showMenu && (
        <>
          <div
            className="fixed inset-0 z-10"
            onClick={() => setShowMenu(false)}
          />
          <div
            className="absolute right-0 mt-1 rounded shadow-lg z-20"
            style={{
              background: '#ece9d8',
              border: '2px solid #7f9db9',
              borderTopColor: '#003c74',
              borderLeftColor: '#003c74',
              minWidth: '200px'
            }}
          >
            <button
              onClick={handlePrintInventorySummary}
              className="w-full text-left px-4 py-2 hover:bg-blue-100 transition-colors"
              style={{
                fontFamily: 'Tahoma, sans-serif',
                fontSize: '13px',
                borderBottom: '1px solid #7f9db9'
              }}
            >
              Inventory Summary
            </button>
            <button
              onClick={handlePrintAllUnits}
              className="w-full text-left px-4 py-2 hover:bg-blue-100 transition-colors"
              style={{
                fontFamily: 'Tahoma, sans-serif',
                fontSize: '13px'
              }}
            >
              All Units List
            </button>
          </div>
        </>
      )}
    </div>
  );
}

export function PrintUnitLabel({ unit }: { unit: Unit }) {
  const { layout } = useWarehouse();
  const [qrCodeUrl, setQrCodeUrl] = useState('');

  useEffect(() => {
    // Generate QR code with unit information
    const unitData = JSON.stringify({
      id: unit.id,
      serialNumber: unit.serialNumber,
      brand: unit.brand,
      model: unit.model
    });

    QRCode.toDataURL(unitData, { width: 200 }).then(url => {
      setQrCodeUrl(url);
    });
  }, [unit]);

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const zoneName = layout.zones.find(z => z.id === unit.location.zone)?.name || unit.location.zone;
    const getLocationText = () => {
      if (unit.location.type === 'floor') {
        return zoneName;
      } else {
        return `${zoneName} - Column ${unit.location.column}, Row ${unit.location.row}, Level ${unit.location.level}`;
      }
    };

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Location Label - ${unit.serialNumber}</title>
          <style>
            @page {
              margin: 0;
              size: 4in 6in;
            }
            body {
              font-family: Arial, sans-serif;
              padding: 0.25in;
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              height: 100vh;
            }
            .label {
              border: 3px solid #000080;
              padding: 20px;
              text-align: center;
              background: white;
            }
            h1 {
              margin: 0 0 10px 0;
              font-size: 24px;
              color: #000080;
            }
            h2 {
              margin: 5px 0;
              font-size: 18px;
            }
            .qr-code {
              margin: 15px 0;
            }
            .info {
              margin: 10px 0;
              font-size: 14px;
            }
            .location {
              font-size: 16px;
              font-weight: bold;
              margin-top: 15px;
              padding: 10px;
              background: #f5f5f5;
              border: 2px solid #7f9db9;
            }
          </style>
        </head>
        <body>
          <div class="label">
            <h1>WAREHOUSE INVENTORY</h1>
            <h2>${unit.brand} ${unit.model}</h2>

            <div class="qr-code">
              <img src="${qrCodeUrl}" alt="QR Code" />
            </div>

            <div class="info">
              <strong>Serial Number:</strong><br/>
              ${unit.serialNumber}
            </div>

            ${unit.equipmentNumber ? `
              <div class="info">
                <strong>Equipment #:</strong> ${unit.equipmentNumber}
              </div>
            ` : ''}

            <div class="location">
              ${getLocationText()}
            </div>

            <div class="info" style="margin-top: 15px; font-size: 12px; color: #666;">
              ${new Date().toLocaleDateString()}
            </div>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  return (
    <button
      onClick={handlePrint}
      className="text-white font-bold py-2 px-4 rounded transition-all text-sm"
      title="Print Location Label"
      style={{
        background: 'linear-gradient(to bottom, #87ceeb 0%, #4169e1 50%, #1e90ff 100%)',
        border: '2px solid #1e90ff',
        borderTopColor: '#b0d4ff',
        borderLeftColor: '#b0d4ff',
        textShadow: '1px 1px 1px rgba(0,0,0,0.3)',
        fontFamily: 'Tahoma, sans-serif'
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.background = 'linear-gradient(to bottom, #a0d8f0 0%, #5a7fe6 50%, #3da0ff 100%)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.background = 'linear-gradient(to bottom, #87ceeb 0%, #4169e1 50%, #1e90ff 100%)';
      }}
    >
      Print Label
    </button>
  );
}

export function PrintUnitDetail({ unit }: { unit: Unit }) {
  const { layout } = useWarehouse();

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const zoneName = layout.zones.find(z => z.id === unit.location.zone)?.name || unit.location.zone;
    const getLocationText = () => {
      if (unit.location.type === 'floor') {
        return zoneName;
      } else {
        return `${zoneName} - Column ${unit.location.column}, Row ${unit.location.row}, Level ${unit.location.level}`;
      }
    };

    const formatCurrency = (value: number) => {
      return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);
    };

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Unit Detail - ${unit.serialNumber}</title>
          <style>
            @page { margin: 0.5in; }
            body {
              font-family: Arial, sans-serif;
              padding: 20px;
            }
            h1 {
              color: #000080;
              border-bottom: 3px solid #000080;
              padding-bottom: 10px;
            }
            .section {
              margin: 20px 0;
              padding: 15px;
              border: 2px solid #7f9db9;
              background: #f5f5f5;
            }
            .section h2 {
              margin-top: 0;
              color: #000080;
              border-bottom: 1px solid #7f9db9;
              padding-bottom: 5px;
            }
            .field {
              display: grid;
              grid-template-columns: 150px 1fr;
              padding: 8px 0;
              border-bottom: 1px solid #ddd;
            }
            .field-label {
              font-weight: bold;
            }
            .status {
              display: inline-block;
              padding: 5px 15px;
              background: #90ee90;
              border: 2px solid #228b22;
              border-radius: 4px;
              font-weight: bold;
            }
            .photo {
              max-width: 400px;
              margin: 10px 0;
              border: 2px solid #7f9db9;
            }
            .footer {
              margin-top: 40px;
              text-align: center;
              font-size: 12px;
              color: #666;
            }
          </style>
        </head>
        <body>
          <h1>Unit Detail Report</h1>
          <p><strong>Report Date:</strong> ${new Date().toLocaleString()}</p>

          <div class="section">
            <h2>Basic Information</h2>
            <div class="field">
              <span class="field-label">Serial Number:</span>
              <span>${unit.serialNumber}</span>
            </div>
            <div class="field">
              <span class="field-label">Brand:</span>
              <span>${unit.brand}</span>
            </div>
            <div class="field">
              <span class="field-label">Model:</span>
              <span>${unit.model}</span>
            </div>
            ${unit.equipmentNumber ? `
              <div class="field">
                <span class="field-label">Equipment Number:</span>
                <span>${unit.equipmentNumber}</span>
              </div>
            ` : ''}
            ${unit.fleetNumber ? `
              <div class="field">
                <span class="field-label">Fleet Number:</span>
                <span>${unit.fleetNumber}</span>
              </div>
            ` : ''}
            <div class="field">
              <span class="field-label">Status:</span>
              <span class="status">${unit.status}</span>
            </div>
            ${unit.condition ? `
              <div class="field">
                <span class="field-label">Condition:</span>
                <span>${unit.condition}</span>
              </div>
            ` : ''}
          </div>

          <div class="section">
            <h2>Location</h2>
            <div class="field">
              <span class="field-label">Location:</span>
              <span>${getLocationText()}</span>
            </div>
          </div>

          ${unit.purchasePrice || unit.purchaseDate || unit.supplier ? `
            <div class="section">
              <h2>Financial Information</h2>
              ${unit.purchasePrice ? `
                <div class="field">
                  <span class="field-label">Purchase Price:</span>
                  <span>${formatCurrency(unit.purchasePrice)}</span>
                </div>
              ` : ''}
              ${unit.purchaseDate ? `
                <div class="field">
                  <span class="field-label">Purchase Date:</span>
                  <span>${new Date(unit.purchaseDate).toLocaleDateString()}</span>
                </div>
              ` : ''}
              ${unit.supplier ? `
                <div class="field">
                  <span class="field-label">Supplier:</span>
                  <span>${unit.supplier}</span>
                </div>
              ` : ''}
            </div>
          ` : ''}

          ${unit.notes ? `
            <div class="section">
              <h2>Notes</h2>
              <p>${unit.notes}</p>
            </div>
          ` : ''}

          <div class="section">
            <h2>Tracking Information</h2>
            ${unit.createdDate ? `
              <div class="field">
                <span class="field-label">Date Added:</span>
                <span>${new Date(unit.createdDate).toLocaleString()}</span>
              </div>
            ` : ''}
            ${unit.addedBy ? `
              <div class="field">
                <span class="field-label">Added By:</span>
                <span>${unit.addedBy}</span>
              </div>
            ` : ''}
            ${unit.updatedDate ? `
              <div class="field">
                <span class="field-label">Last Updated:</span>
                <span>${new Date(unit.updatedDate).toLocaleString()}</span>
              </div>
            ` : ''}
          </div>

          ${unit.photoUrl ? `
            <div class="section">
              <h2>Photo</h2>
              <img src="${unit.photoUrl}" alt="Unit photo" class="photo" />
            </div>
          ` : ''}

          <div class="footer">
            <p>Generated by Warehouse Management System</p>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.print();
  };

  return (
    <button
      onClick={handlePrint}
      className="text-white font-bold py-2 px-4 rounded transition-all text-sm"
      title="Print Unit Detail"
      style={{
        background: 'linear-gradient(to bottom, #87ceeb 0%, #4169e1 50%, #1e90ff 100%)',
        border: '2px solid #1e90ff',
        borderTopColor: '#b0d4ff',
        borderLeftColor: '#b0d4ff',
        textShadow: '1px 1px 1px rgba(0,0,0,0.3)',
        fontFamily: 'Tahoma, sans-serif'
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.background = 'linear-gradient(to bottom, #a0d8f0 0%, #5a7fe6 50%, #3da0ff 100%)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.background = 'linear-gradient(to bottom, #87ceeb 0%, #4169e1 50%, #1e90ff 100%)';
      }}
    >
      Print Details
    </button>
  );
}
